apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-staging

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

configMapGenerator:
  - name: webapp-config
    envs:
      - configmap.env

secretGenerator:
  - name: webapp-secret
    envs:
      - secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
